name: Build

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Update package list and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libvorbis-dev libogg-dev libflac-dev libfreetype6-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BlueBlast-Linux
          path: build/bin/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BlueBlast-Windows
          path: build/bin/